<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "google_for_jobs"
 *
 * Auto generated by Extension Builder 2019-09-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Google for Jobs',
    'description' => 'Render Google for Jobs structured data.',
    'category' => 'plugin',
    'author' => 'Michael Kunst',
    'author_email' => 'kunst@pega-sus.de',
    'author_company' => 'PEGASUS Werbeagentur GmbH',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
